### ISSUE TITLE
BaseFragment injection

### ISSUE THREAD

**Issue by Minkfan** [dpolishuk/weather-android#1]
I want, for example, use `Bus` in every fragment, so I will move it to `BaseFragment`.
But if I am not explicitly doing `((BusSubcomponent) getComponent()).inject(this);` in `WeatherFragment` (and/or removing `inject` from `BusSubcomponent` interface), I get an error.
What should I do to fix this? Sorry if the question is stupid, I am really new to DI.

**Comment by dpolishuk** [comment]
@Minkfan 
I used bus in this project just to show how to achieve module overriding approach.
In your case, you need to provide Bus on Application level (AppModule or just to mark your Bus wrapper as @Singleton (construction injection)).

In dagger2 you can't inject the same component twice, so you need to inject all your things on upper level, like WeatherFragment, or MainActivity, but not to BaseFragment.

BTW: you can avoid injection and use direct calls from component:

``` java
@Singleton
@Component(modules = { AppModule.class })
public interface AppComponent {
  Bus bus();
}
```

``` java
public class MainActivity extends BaseActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    getComponent().bus().post(new YourEvent());
  }
}
```

Sorry for so delayed answer.

**Comment by Minkfan** [comment]
@dpolishuk 
Thank you for explanation!
